### ISSUE TITLE
Cannot start a clean project

### ISSUE THREAD

**Issue by ormedo** [GeekyAnts/vue-native-core#16]
I cant start a simple proyect:

HelloWorld@0.1.0 start /Users/manuelfrancogiraldez/Documents/proyectos/JavaScript/Vue-Native/HelloWorld
> react-native-scripts start

17:05:48: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
        
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HelloWorld@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the HelloWorld@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manuelfrancogiraldez/.npm/_logs/2018-06-13T15_05_48_943Z-debug.log

The log content is here:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/node_modules/node/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle HelloWorld@0.1.0~prestart: HelloWorld@0.1.0
6 info lifecycle HelloWorld@0.1.0~start: HelloWorld@0.1.0
7 verbose lifecycle HelloWorld@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle HelloWorld@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/manuelfrancogiraldez/Documents/proyectos/JavaScript/Vue-Native/HelloWorld/node_modules/.bin:/Users/manuelfrancogiraldez/Documents/proyectos/Flutter/SDK/flutter/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle HelloWorld@0.1.0~start: CWD: /Users/manuelfrancogiraldez/Documents/proyectos/JavaScript/Vue-Native/HelloWorld
10 silly lifecycle HelloWorld@0.1.0~start: Args: [ '-c', 'react-native-scripts start' ]
11 silly lifecycle HelloWorld@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle HelloWorld@0.1.0~start: Failed to exec start script
13 verbose stack Error: HelloWorld@0.1.0 start: `react-native-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid HelloWorld@0.1.0
15 verbose cwd /Users/manuelfrancogiraldez/Documents/proyectos/JavaScript/Vue-Native/HelloWorld
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/lib/node_modules/node/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.4.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error HelloWorld@0.1.0 start: `react-native-scripts start`
22 error Exit status 1
23 error Failed at the HelloWorld@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

what i do worng?

**Comment by ormedo** [comment]
I Close the issue,
Just execute the "sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288" and go ok.
