### ISSUE TITLE
no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by mehdikhody** [GeekyAnts/vue-native-core#95]
```
vue-native init test
---------------------------------------------------------
Installed Crna Version create-react-native-app version: 2.0.2
Creating Vue-Native test App
[19:28:17] Input is required, but expo is in non-interactive mode.
Required input:
> Choose a template:
C:\Users\Username\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:140
  process.chdir(projectName);
          ^

Error: ENOENT: no such file or directory, uv_chdir
    at handleAndAddVueNativePackageDependencySync (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:140:11)
    at createVueNativeProject (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:101:3)
    at init (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:76:7)
    at Command.<anonymous> (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:59:7)
    at Command.listener (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\Mehdi\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:63:9)
```

**Comment by neeraj-singh47** [comment]
@mehdikhody Did you receive any options for template? if yes, What did you choose?

**Comment by vickey999** [comment]
I am also getting same issue

> Choose a template:
internal/process/main_thread_only.js:31
    return _chdir(...args);
           ^

Error: ENOENT: no such file or directory, chdir 'myapplication'
    at process.chdir (internal/process/main_thread_only.js:31:12)
    at handleAndAddVueNativePackageDependencySync (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:140:11)
    at createVueNativeProject (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:101:3)
    at init (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:76:7)
    at Command.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:59:7)
    at Command.listener (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:63:9)

**Comment by neeraj-singh47** [comment]
Try updating vue-native-cli to latest verion and creating an app.

**Comment by OzanKurt** [comment]
It's not a solution.

**Comment by OzanKurt** [comment]
@neeraj-singh47

**Comment by ndvbd** [comment]
Any solutions?

**Comment by Zacharygagnier** [comment]
I am currently on windows, I've installed all the dependencies, restarted, and I am getting this issue, unable to proceed.

**Comment by lunkkun** [comment]
This is still a problem. Tested on Windows 10.

**Comment by qodehub-nanadjei** [comment]
Am also having the same issue.

**Comment by lunkkun** [comment]
Still not working for me on Windows 10. Please reopen this issue.

Tested with:
npm@6.11.2
expo-cli@3.0.10
vue-native-cli@0.1.0
